version: "3"

includes:
  lint: tasks/lint.yml
  compile: tasks/compile.yml

tasks:
  clean:
    desc: Clean the project
    cmds:
      - python scripts/clean.py

  build:
    desc: Build the project
    deps:
      - compile
    cmds:
      - poetry build -n
    sources:
      - pyproject.toml
      - poetry.lock
      - whiteproto/**/*.py
    targets:
      - dist/whiteproto-*.tar.gz
      - dist/whiteproto-*.whl
    status:
      - test -f dist/whiteproto-*.tar.gz
      - test -f dist/whiteproto-*.whl

  default:
    desc: Run clean build
    cmds:
      - task: clean
      - task: build
