version: "3"

tasks:
  flake8:
    desc: Lint the project with flake8
    cmds:
      - poetry run flake8 --benchmark --statistics whiteproto

  mypy:
    desc: Lint the project with mypy
    cmds:
      - poetry run mypy --config-file mypy.ini whiteproto

  isort:
    desc: Lint the project with isort
    cmds:
      - poetry run isort --check-only --diff whiteproto

  black:
    desc: Lint the project with black
    cmds:
      - poetry run black --check --diff whiteproto

  default:
    desc: Lint the project
    deps:
      - flake8
      # - mypy
      - isort
      - black
