name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: task dependencies

    - name: Run linters
      run: task lint
